name: Dotnet format check on PRs

on:
  pull_request:
    branches: ["main"]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    name: Check current formatting

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Format files
        run: dotnet format --verify-no-changes --verbosity diagnostic

