name: "Build .Net and generate GraphQL schema"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: restore nuget packages
        run: dotnet restore

      - name: build solution
        run: dotnet build --no-restore

      - name: Try to generate GraphQL schema
        run: dotnet run --project ./src/Backend/Backend.Api/ -- schema export
